### PR TITLE
update: refactor the global limit

### PR DESCRIPTION
**Pull request by thank243**
fix: some log prefix

It an enhance device limit. Redis just use to sync local ipMap. If global limit is enabled. The online report will faliure. All enabled nodes will report the device from redis.

### CODE REVIEW

**Comment by thank243** [comment]
I have refactored the global limit feat. Please check it if work normally.@pocketW @Github-Aiko

**Comment by Github-Aiko** [comment]
@thank243 Where do I set the number of devices?

**Comment by thank243** [comment]
> @thank243 Where do I set the number of devices?

local device limit

**Comment by Github-Aiko** [comment]
I am testing it and doesn't work !!!

**Comment by Github-Aiko** [comment]
Screen Shot 2022-11-27 at 17 56 32

Logs

**Comment by Github-Aiko** [comment]
I have limit 2 node = 1 but when I connect to it, 2 IP 2 node still works normally.

**Comment by Github-Aiko** [comment]
Limit = 1

**Comment by thank243** [comment]
trun debug and paste to gist

> I have limit 2 node = 1 but when I connect to it, 2 IP 2 node still works normally.

**Comment by Github-Aiko** [comment]
> trun debug and paste to gist
> 
> > I have limit 2 node = 1 but when I connect to it, 2 IP 2 node still works normally.

#123

**Comment by thank243** [comment]
@pocketW Hello, If we don't use this sync.map, we should maint 2 different user oneline map. It'll become complex.
https://github.com/XrayR-project/XrayR/blob/d320aadb54fd19764d0f3404ef30468b01b40f03/service/controller/controller.go#L604

As this condition, It couldn't report zero online.

So, should we really need two user maps?

**Comment by thank243** [comment]
Ok, I will revert this commit.

**Pull request merged**
