### PR TITLE
feat: unify trojan transport & add ss2022 related config

### PR DESCRIPTION
**Pull request by M1Screw**

### CODE REVIEW

**Comment by thank243** [comment]
Do you make any compatibility with old version?

**Comment by M1Screw** [comment]
`mu_*` options are for ShadowsocksR only and have been removed from sspanel a long time ago, considering XrayR no longer supports the SSR protocol it can be safely removed.

However, the `method` option is a new param used exclusively for the ss2022 server type, which will be available in the 2023.6 release.

The `grpc` param is created by XrayR's origin author, RManLuo, which is not consistent with the transport config of Vmess node type, this param will be dropped in 2023.6, operator of old version sspanel can update their custom config from `"grpc": "1"` to `"network": "grpc"` without breaking WebAPI compatibility.

**Comment by M1Screw** [comment]
And to be honest, XrayR should drop the legacy server config method, and bump the minimal sspanel compatibility level to 2021.11 or just add an `OldSSPanel` as a separate node type, allowing the WebAPI adapter to follow upstream changes.

With more custom config related updates in the future and a versioned WebAPI feature level, there will be a limit when comes to maintaining compatibility with old and outdated versions of sspanel(especially those theme-based forks aka. Metron, Malio, etc.), 

We will maintain a fork to include an updated WebAPI adapter and open pull requests if possible, however, it's up to you to decide if you want the maximum compatibility or follow the development of sspanel and make sure XrayR is usable for new installations. 

The current stable release(0.9.0) has been broken since the last time we sunset a few legacy API endpoints, I have asked you multiple times to tag a new release, however, those comments are ignored. It's a shame we have to do the hard fork to fix a minor issue like this.

**Comment by thank243** [comment]
Hello, @M1Screw ,you can pr a new sspanel api same like new v2board. Waiting for you good work.

**Comment by M1Screw** [comment]
Well, you merge this one first, this includes changes that will come in the next stable release. Meanwhile please consider separating the custom config disabled/enabled sspanel type, we will make changes to the current sspanel panel type since it's not a complete redesign, unlike v2board's new API.

**Comment by thank243** [comment]
Thx for your pr. And I just optimise the determine of null custom_config. Could you test it works as expect?

**Comment by M1Screw** [comment]
>Could you test it works as expect?

Yes.

**Pull request merged**
