### PR TITLE
fix routes for newV2board(uniproxy)

### PR DESCRIPTION
**Pull request by Yuzuki616**

### CODE REVIEW

**Comment by thank243** [comment]
You should check the latest dev on v2board.

**Comment by Yuzuki616** [comment]
But your not have any version support 1.7.1's routes.I think supporting the dev version first is a not good idea.

**Comment by thank243** [comment]
The release version support.

**Comment by Yuzuki616** [comment]
You should be check your code again. The match field need split.

**Comment by thank243** [comment]
It's doesn't matter. All feat will sync with 1.7.2

**Comment by Yuzuki616** [comment]
I don't want pr again. But I think you should add a tip to releases page  to remind users of 1.7.1(if you don't want fix it.).

**Pull request closed without merging**
