### PR TITLE
fix: global limit will failure on some situation

### PR DESCRIPTION
**Pull request by thank243**
fix: typo

@pocketW 
@Github-Aiko

### CODE REVIEW

**Comment by thank243** [comment]
> 

Its a feat, not remove.

**Comment by Github-Aiko** [comment]
> Its a feat, not remove.

ApiHost On logs 🐞 ,

**Comment by thank243** [comment]
If you are on single node multi panels. It is a useful feature.

**Comment by Github-Aiko** [comment]
I have test it , And It not works , Ip no Limit . Runing all

**Comment by thank243** [comment]
Confirm you are use the latest version？

**Pull request merged**
