### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by Github-Aiko**
@thank243 ....

### CODE REVIEW

**Comment by thank243** [comment]
https://github.com/XrayR-project/XrayR/blob/6477ef6c447611a310937b42bbbd4507b09a7fb4/common/limiter/limiter.go#L259-L267
This func has alrealdy throw a error when any problems on redis.

**Comment by Github-Aiko** [comment]
okay Thanks 👍

**Comment by Github-Aiko** [comment]
DNS resolution function does not work in V2board you can review.

**Comment by thank243** [comment]
> DNS resolution function does not work in V2board you can review.

You can use this version to test https://ufile.io/pssryslv

**Comment by Github-Aiko** [comment]
> > DNS resolution function does not work in V2board you can review.
> 
> You can use this version to test https://ufile.io/pssryslv

Jan 01 16:01:41 host-185-14-47-39 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 5.
Jan 01 16:01:41 host-185-14-47-39 systemd[1]: Stopped XrayR Service.
Jan 01 16:01:41 host-185-14-47-39 systemd[1]: Started XrayR Service.
Jan 01 16:01:41 host-185-14-47-39 XrayR[871504]: /usr/local/XrayR/XrayR: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/XrayR/XrayR)
Jan 01 16:01:41 host-185-14-47-39 XrayR[871504]: /usr/local/XrayR/XrayR: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/XrayR/XrayR)
Jan 01 16:01:41 host-185-14-47-39 systemd[1]: XrayR.service: Main process exited, code=exited, status=1/FAILURE
Jan 01 16:01:41 host-185-14-47-39 systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by thank243** [comment]
https://ufile.io/ch1z5kss

**Pull request closed without merging**
